---
- name: APT & misc
  hosts: all
  tasks:

  - name: apt maintenance & install
    ansible.builtin.apt:
      update_cache: true
      autoclean: yes
      name: 
        - curl
        - dnsutils
        - nano
        - tree
        - vim
      state: present
      autoremove: yes
    become: yes

  - name: copy vimrc to client
    ansible.builtin.copy:
      src: files/vimrc
      dest: ~/.vimrc
...
