---
- name: proxy
  hosts: proxy
  tasks:

    - name: APT update cache and make sure haproxy installed
      become: yes
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 86400
        name: haproxy
        state: present

    - name: upload haproxy.cfg
      become: yes
      ansible.builtin.copy:
        src: files/proxy/haproxy.cfg
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: '0660'
        validate: haproxy -f %s -c
      notify:
        - Restart haproxy

    - name: haproxy service
      become: yes
      ansible.builtin.service:
          name: haproxy
          enabled: yes
          state: started

  handlers:
    - name: Restart haproxy
      become: yes
      ansible.builtin.service:
        name: haproxy
        state: restarted
...
